language: c
compiler:
  - gcc
  - clang
script: extras/build-tests/nix/build $BUILDCONFIG
env:
  - BUILDCONFIG=""
  - BUILDCONFIG="system-cares"
  - BUILDCONFIG="system-cares system-curl"
  - BUILDCONFIG="local-curl"
